name: PHP build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 5.3, 7.4, 8.0, 8.1, 8.2 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Running test
        run: composer run-script test
